[theme]
primaryColor = "#2db3ed"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#e9f4fb"
textColor = "#222222"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = false
